### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by THEJESH19** [opensearch-project/spring-data-opensearch#102]
### What is the bug?
We are currently trying to migrate the spring boot application from elasticsearch to opensearch and using the dependency of "spring-data-opensearch". 

We are getting an error regarding the VersionType class when we run the application.

This is caused from the entity classes that has @Document defined in them which uses the org.springframework.data.elasticsearch.annotations.Document which is internally using VersionType class from "org.elasticsearch.index.VersionType". Which is the root cause of the issue as 'index' folder is not found in the elasticsearch dependency.

### How can one reproduce the bug?
Use the spring boot parent version 2.5.13 and java version 11. 
With maven dependency of "spring-data-opensearch" / 'spring-data-opensearch-starter". 

Your application should have a entity file with @Document annotation. When you run the application you will see the error with VersionType class

### What is the expected behavior?
Migration from elasticsearch to opensearch should not cause any issues and the transaction must be seemless

### What is your host/environment?
_macOSVentura 13.2.1

### Do you have any additional context?
_This issue is caused when migrating the elasticsearch to opensearch

**Comment by reta** [comment]
@THEJESH19 please check the https://github.com/opensearch-project/spring-data-opensearch#compatibility-matrix, the minimal supported version is Spring Boot 3.x / Spring Data Elastic Search 5.x / Spring Framework 6.x
