### ISSUE TITLE
[FEATURE] Add integration tests across the compatibility matrix

### ISSUE THREAD

**Issue by dblock** [opensearch-project/spring-data-opensearch#12]
### Is your feature request related to a problem?

We document the following compatibility matrix, https://github.com/opensearch-project/spring-data-opensearch#compatibility-matrix. But does it really work?

### What solution would you like?

Add integration tests that boot OpenSearch containers and test this project against it.

**Comment by rursprung** [comment]
it currently lists OpenSearch 1.x as being compatible, does that mean that it should also be compatible with ES 7.10.2? that'd be perfect, to have a clear migration roadmap (i.e. update clients first, then the server; otherwise a lock-step upgrade would be needed)

**Comment by dblock** [comment]
> it currently lists OpenSearch 1.x as being compatible, does that mean that it should also be compatible with ES 7.10.2? that'd be perfect, to have a clear migration roadmap (i.e. update clients first, then the server; otherwise a lock-step upgrade would be needed)

@reta do you know? we should add integ tests anyway if we want to make sure

**Comment by reta** [comment]
The OpenSearch 1.x should be supported (I checked that at the time of original pull request) BUT there is one catch: the baseline JDK for the project is 17 (what I am trying to say is that it is very likely 2.0 would be the minimal OS version in the wild, I could be mistaken). Regarding, ES 7.10.2, I think it should be compatible (although I did not test that) but there is no real reason to use `spring-data-opensearch`: the `spring-data-elasticsearch` covers that (and the flip from ES to OS would be only minimal configuration changes).

**Comment by rursprung** [comment]
> Regarding, ES 7.10.2, I think it should be compatible (although I did not test that) but there is no real reason to use `spring-data-opensearch`: the `spring-data-elasticsearch` covers that (and the flip from ES to OS would be only minimal configuration changes).

the use-case for that would really be for migrations of current setups running with ES 7.10.2 & spring-data-elasticsearch: if you upgrade ES to OpenSearch 2.x first then spring-data-elasticsearch will fail. so to do this as an online migration (instead of a big-bang approach) you'd first upgrade the clients to use spring-data-opensearch and only afterwards do the ES to OpenSearch 2.x migration. not sure how many people have a need for that though.
