### ISSUE TITLE
[BUG] Compatibility with Spring Boot 3.1.0 and spring-data-elasticsearch 3.1.0

### ISSUE THREAD

**Issue by indyarni** [opensearch-project/spring-data-opensearch#134]
When upgrading our Spring Boot Projects to Spring Boot 3.1.0 there occurred an IllegalAccessException in 
spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/NativeSearchQueryBuilder.java 
on field indicesOptions. This is because in spring-data-elasticsearch 5.1.0 this field became private in the base class BaseQueryBuilder.

spring-data-opensearch itself depends on spring-data-elasticsearch 5.0.5, where the problem does not occur yet. But when a Spring Boot app includes spring-data-opensearch as dependency, then Spring Boot's spring-boot-dependencies parent declares spring-data-elasticsearch 5.1.0 as managed dependency, overriding the dependency version:
https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/3.1.0/spring-boot-dependencies-3.1.0.pom

The only valid workaround that works for us is explicitly declaring spring-data-elasticsearch 5.0.5 as dependency in every project (which is pretty cumbersome).

Here is an article about the general problem we have and several possible workarounds: https://spring.io/blog/2016/04/13/overriding-dependency-versions-with-spring-boot

The long term solution would probably be to change the Code of NativeSearchQueryBuilder to avoid the IllegalAccessException.

**Comment by renatosilvarosa** [comment]
@reta, I would like to work on this issue and I've already created a fork for that. I must simply create the PR when it's ready, or is there any previous process?

**Comment by reta** [comment]
@renatosilvarosa sure please go ahead, thank you for taking it

> I must simply create the PR when it's ready, or is there any previous process?

Just a pull request, thank you.

**Comment by reta** [comment]
@renatosilvarosa there are quite a few demands to get that done, the pull request is out

**Comment by renatosilvarosa** [comment]
@reta No worries, I had just started, and due to my lack of knowledge of the internals, I was taking some time to understand. I'll be glad to look into your PR and see how you resolved the issue.

**Comment by rosti-il** [comment]
Hi there. When a new version of the `spring-data-opensearch` with this fix is planned to be released or could you make this release soon? Will it work with the latest Spring Boot 3.1.1 as well?

**Comment by reta** [comment]
@rosti-il should be there (on Central) soon, https://github.com/opensearch-project/spring-data-opensearch/releases/tag/v1.2.0
