### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by noam-shoef** [opensearch-project/spring-data-opensearch#136]
### Is your feature request related to a problem?

I was trying to turn off the sniffer functionality but found it impossible.
I was trying to extend the configuration or import only those I wanted but for some reason OpenSearchRestClientConfigurations is not public which make it difficult/impossible to extend or even import if you want to use only some of the configurations.

### What solution would you like?
please make this classes public so that it would be easy to extend.

### What alternatives have you considered?

Maybe make the auto configuration more configurable but even then I'd think that this class should be public.

**Comment by reta** [comment]
@noam-shoef to turn off sniffer, please remove the `sniffer` dependency

**Comment by reta** [comment]
> I only have spring-data-opensearch-starter and spring-data-opensearch in my dependancy.

```
        <dependency>
            <groupId>org.opensearch.client</groupId>
            <artifactId>spring-data-opensearch-starter</artifactId>
            <exclusions>
            	<exclusion>
            		<groupId>org.opensearch.client</groupId>
            		<artifactId>opensearch-rest-client-sniffer</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>
```
No need to change the configuration
