### ISSUE TITLE
[FEATURE] Support synonyms in seperate txt-file

### ISSUE THREAD

**Issue by bjornhun** [opensearch-project/spring-data-opensearch#169]
### Is your feature request related to a problem?
I need to add a filter to my settings with a long list of synonyms. Ideally, I would like to store this in a separate synonyms.txt file, and reference it like this:

`      "synonym_filter": {
        "type": "synonym",
        "synonyms_path": "synonyms.txt"
      }`

But then I get this error:
`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"IOException while reading synonyms_path_path: /usr/share/opensearch/config/synonyms.txt"}],"type":"illegal_argument_exception","reason":"IOException while reading synonyms_path_path: /usr/share/opensearch/config/synonyms.txt","caused_by":{"type":"no_such_file_exception","reason":"/usr/share/opensearch/config/synonyms.txt"}},"status":400}
`

### What solution would you like?
Look for the referenced synonyms.txt file in my resources folder, and not in /usr/share/opensearch/config.

### What alternatives have you considered?
The alternative is to have the list of synonyms directly in the filter definition, but this will bloat my settings.json substantially.

**Comment by bjornhun** [comment]
It seems like this should already be possible: https://github.com/opensearch-project/spring-data-opensearch/blob/a89490141203cc5b75180ff0099d4d4cb9e6fe24/spring-data-opensearch/src/test/resources/synonyms/settings-with-external-file.json#L17

However, I can't see that this settings-file is actually used in any tests.

**Comment by reta** [comment]
@bjornhun you would like to use `synonyms.txt` within tests, correct?

**Comment by bjornhun** [comment]
I would like to use it in production ideally.

**Comment by reta** [comment]
> t seems that the file is currently expected to be on the Opensearch server

The file should be always on OpenSearch server, this is by design [1] (that OpenSearch inherited from Elasticsearch).

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/search-with-synonyms.html#synonyms-store-synonyms-file
