### ISSUE TITLE
[PROPOSAL] Build with Gradle

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/spring-data-opensearch#17]
### What are you proposing?

Use a Gradle build for this project.

### What users have asked for this feature?

As a developer in the OpenSearch project, I'm familiar with Gradle builds.

### What problems are you trying to solve?

Make it easier for developers from OpenSearch to start contributing.

### Alteratives

* Include a Maven Wrapper
* Remove the Spring parent POM since this is an OpenSearch project, not a Spring project.

**Comment by reta** [comment]
@dlvenable @dblock I will take this one since all our publishing scritps / Jenkins jobs are Gradle focused, we would need that to publish SNAPSHOTS / milestones / releases.
