### ISSUE TITLE
[BUG] bean named 'elasticsearchTemplate' that could not be found.

### ISSUE THREAD

**Issue by jsanchezerreka** [opensearch-project/spring-data-opensearch#188]
### What is the bug?
A component required a bean named 'elasticsearchTemplate' that could not be found.

### How can one reproduce the bug?
Reproducing readme steps

**Comment by reta** [comment]
@jsanchezerreka please take a look at https://github.com/acm19/aws-request-signing-apache-interceptor, since RHCL uses ApacheHttpClient under the hood, you have an option to provide your own with interceptors added

**Comment by jsanchezerreka** [comment]
I've try it and it works like a charm!!! Now I'm connected to Opensearch with no problems. Thanks so much for the support 👍 👍

**Comment by firatluvu** [comment]
@reta @jsanchezerreka  What is the solution here? I really appreciate to see sample implementation since the issue title and the suggestion offered by @reta seems unrelated.

**Comment by reta** [comment]
> @reta @jsanchezerreka What is the solution here? I really appreciate to see sample implementation since the issue title and the suggestion offered by @reta seems unrelated.

@firatluvu this is non issue as per reporter

> Sorry about this, I realise by looking to version matrix and my own spring boot version that I was outdated (version 2.6.6).

**Comment by firatluvu** [comment]
@reta Thanks for the clarification and maintaining this repository!
