### ISSUE TITLE
[FEATURE] Migrate from Apache Maven to Gradle

### ISSUE THREAD

**Issue by reta** [opensearch-project/spring-data-opensearch#20]
### Is your feature request related to a problem?
The project currently is using Apache Maven as a build tool (due to the fact that the original project https://github.com/spring-projects/spring-data-elasticsearch is also based on Apache Maven), but the OpenSearch project porfolio is using Gradle.

### What solution would you like?
Migrate from Apache Maven to Gradle as a build tool

### What alternatives have you considered?
Keep Apache Maven

### Do you have any additional context?
N/A

**Comment by dblock** [comment]
Dup of https://github.com/opensearch-project/spring-data-opensearch/issues/17
