### ISSUE TITLE
[BUG] OpenSearchRestTemplate increases the usage of non-heap memory

### ISSUE THREAD

**Issue by lopiter** [opensearch-project/spring-data-opensearch#204]
### What is the bug?
I am using OpenSearchRestTemplate with a Kotlin + Spring combination.
I'm passing a class as the second parameter to search, and it seems to increase the usage of non-heap memory.

### How can one reproduce the bug?
While operating the service for a long time, I've noticed that extensive use of search queries leads to an increase in the non-heap memory area

### What is the expected behavior?
I think it's necessary to ensure that the non-heap memory does not increase

### What is your host/environment?
linux / org.springframework.boot ( 3.1.2)

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by dblock** [comment]
@lopiter Do you have a simple(r) repro? Some code that shows the problem?

**Comment by reta** [comment]
> While operating the service for a long time, I've noticed that extensive use of search queries leads to an increase in the non-heap memory area

How do you measure that? Could you share JVM NMT summary? Thank you

**Comment by reta** [comment]
No details from the user, closing this one
