### ISSUE TITLE
[BUG]Spring boot opensearch dependency is running into error 

### ISSUE THREAD

**Issue by saravanKN** [opensearch-project/spring-data-opensearch#225]
Hello team,

When I try to use spring data opensearch dependency I get `BeanDefinitionStoreException` error

```
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [/Users/develop/opensearch/spring-client/opensearch-test/target/classes/com/opensearchtest/indexing/doc/UsageDocument.class]; nested exception is java.lang.NoClassDefFoundError: org/elasticsearch/index/VersionType
```

I’m using dependency

```
org.opensearch.client
spring-data-opensearch
1.3.0
```

Since elastic and opensearch dependencies cannot be added in same project as it will throw compatibility issue due to library lucene, is there any alternative way to add these libraries that are erroring?

Thanks

**Comment by dblock** [comment]
Where is the elasticsearch dependency coming from? Care to post a small(er) project repro to GitHub?

**Comment by reta** [comment]
@saravanKN I think you have already asked the question here [1] and the answer was provided: the OpenSearch and Elasticsearch clients could not be used at the same time.

https://forum.opensearch.org/t/lucene-compatibility-issue-when-trying-to-use-spring-data-opensearch/17417/4
