### ISSUE TITLE
[BUG] Runtime Error when I Use provided Document annotation

### ISSUE THREAD

**Issue by saravanKN** [opensearch-project/spring-data-opensearch#256]
Im using spring data-opensearch-opensearch lib as mentioned in the screenshot, in that I use one of the annotation called @Document which is internally using org.elasticsearch.index.VersionType, When i compile my project after using Document class I get runtime error saying 
Caused by: java.lang.NoClassDefFoundError: org/elasticsearch/index/VersionType, 

To use this annotation is this class required ? or is there any alternative way to remove this ?

![Screenshot 2024-04-02 at 11 19 42 PM](https://github.com/opensearch-project/spring-data-opensearch/assets/79577845/e0596c52-a59a-4e75-92cb-e2c6722cfd19)

![Screenshot 2024-04-02 at 11 11 42 PM](https://github.com/opensearch-project/spring-data-opensearch/assets/79577845/0f548199-75e3-4b8f-8b05-f026e5588aa9)
![Screenshot 2024-04-02 at 11 16 16 PM](https://github.com/opensearch-project/spring-data-opensearch/assets/79577845/9f317c01-b21b-488d-9441-d0cfaa23570a)
![Screenshot 2024-04-02 at 11 17 48 PM](https://github.com/opensearch-project/spring-data-opensearch/assets/79577845/f0cdbeb1-c055-40df-a972-a881188f7c45)

**Comment by reta** [comment]
@saravanKN Spring Data OpenSearch needs Spring Boot 3.x and Spring Data Elasticsearch 5.x, see please https://github.com/opensearch-project/spring-data-opensearch/blob/main/README.md#compatibility-matrix
