### ISSUE TITLE
[BUG] Version incompability with Spring Boot 3.3.0

### ISSUE THREAD

**Issue by teemupartanen-compile** [opensearch-project/spring-data-opensearch#284]
### What is the bug?
Version 1.4.0 of spring-data-opensearch depends on jackson 2.17 which comes nicely with Spring Boot 3.3.0 dependencies. However, version 1.4.0 is not compatible with spring-data-commons version 3.3.0 since it internally uses methods/classes that are present in spring-data-commons 3.2.6 but not in 3.3.0. 

This makes it very hard to update to Spring Boot 3.3.0 if spring-data-opensearch is used.

Please release a fixed version that is based on Spring Boot 3.3.0.

### How can one reproduce the bug?
_Steps to reproduce the behavior._

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by reta** [comment]
@teemupartanen-compile please check https://github.com/opensearch-project/spring-data-opensearch/blob/main/README.md for compatibility information.
