### ISSUE TITLE
[QUESTION] Can PIT ID change across search requests?

### ISSUE THREAD

**Issue by matheisco** [opensearch-project/spring-data-opensearch#286]
Hi!

I was wondering about the tests in ElasticsearchIntegrationTests.java regarding PIT. In [this test](https://github.com/opensearch-project/spring-data-opensearch/blob/dd29ed386f17c527ac1b6cf5872f3d086af0ca42/spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/core/ElasticsearchIntegrationTests.java#L2637), the PIT ID is reused across multiple requests, without using the one that is returned in the response of the search requests (if I understand the code correctly).

I want to make sure I understand the documentation correctly. In the [ElasticSearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/point-in-time-api.html), they explicitly say that the PIT ID can change across requests:
> The open point in time request and each subsequent search request can return different id; thus always use the most recently received id for the next search request.

Since OpenSearch was a fork of ElasticSearch, I'm wondering if there is a similar constraint for OpenSearch? Or can I be certain that the PIT ID never changes?

Thanks!

**Comment by reta** [comment]
> Since OpenSearch was a fork of ElasticSearch, I'm wondering if there is a similar constraint for OpenSearch? Or can I be certain that the PIT ID never changes?

Hi @matheisco , no sure I understood your question correctly, there could be many PITs open and you could run search request against any of those by providing the respective PIT ID. Does it make sense?

**Comment by matheisco** [comment]
Hi @reta, I understand that part, what I'm unsure of is the PIT ID that OpenSearch returns in the response of a search request:
```
{
    "pit_id": "XYZ",
    "took": 180,
    "timed_out": false,
    "_shards": {
...
```
According to the ElasticSearch docs, subsequent search requests can return different PIT IDs, so I can't keep using the one from the initial PIT creation request.
Not sure if the same is true for OpenSearch...

**Comment by reta** [comment]
> According to the ElasticSearch docs, subsequent search requests can return different PIT IDs, so I can't keep using the one from the initial PIT creation request.

Oh I see, thank you @matheisco , so I would say this: at the moment, the `pit_id` of the response should much the `pit_id` of the request, but I strongly believe that this may change in the future (since there are some unimplemented flows internally), so I think the general answer would be - yes, it could change.

**Comment by matheisco** [comment]
Ok, thanks for the clarification @reta!
