### ISSUE TITLE
No handler for type [flattened] declared on field [requestParameters]

### ISSUE THREAD

**Issue by kedbirhan** [opensearch-project/spring-data-opensearch#305]
for a field type that we want to map to flattened object field, it can be annotated with  `@FieldType.Flattened` which is mapped to "flattened" field type in elasticsearch. But opensearch does not recognize this type since its declared as "flat_object" in Opensearch type. due to this mismatch i am unable to declare flattened obejct type using `org.springframework.data.elasticsearch.annotations.FieldType` any recommendation or workaround  to solve this problem ?

reference 
https://opensearch.org/docs/latest/field-types/supported-field-types/flat-object/
https://www.elastic.co/guide/en/elasticsearch/reference/current/flattened.html
https://docs.spring.io/spring-data/elasticsearch/docs/current/api/org/springframework/data/elasticsearch/annotations/FieldType.html#Flattened

**Comment by reta** [comment]
https://github.com/spring-projects/spring-data-elasticsearch/issues/2942

**Comment by reta** [comment]
Coming in Spring Data Elasticsearch 5.4

**Comment by kedbirhan** [comment]
thanks a lot!

**Comment by reta** [comment]
Since Spring Data Elasticsearch 5.4.0, it is supported using `mappedTypeName` attribute of the `@Field` / `@InnerField` annotation, for example:

```
@Field(type = FieldType.Flattened, mappedTypeName = "flat_object") String flattenedField;
```
