### ISSUE TITLE
[PROPOSAL] why not allow external access to the CriteriaQueryProcessor making it public?

### ISSUE THREAD

**Issue by domenicofasano99** [opensearch-project/spring-data-opensearch#310]
### What are you proposing?
I developed many applications needing access to the CriteriaQueryProcessor to be able to convert an object Criteria in a QueryBuilder one and then convert it into a JSON String, so that it can be used in creating queries with aggregations.
The only problem is that this class (CriteriaQueryProcessor) is not public, is there any reason not to expose it or could it be exposed so that users can use it directly?

### What problems are you trying to solve?
I would like to convert e Criteria query to a QueryBuilder that can do an aggregation on data and to do that I need to use something like this:
 queryToJson(CriteriaQueryProcessor.createQuery(criteriaQuery.getCriteria()), mapper)

**Comment by reta** [comment]
`CriteriaQueryProcessor` is purely a helper class (at least this is how it was designed) and we are closely following Spring Data Elasticsearch on the matter. Please ask the question https://github.com/spring-projects/spring-data-elasticsearch if you need more context.

**Comment by domenicofasano99** [comment]
So instead of these, It's possible create a NativeQuery or a NativeSearchQuery with Criteria and aggregation and run it with the OpensearchTemplate?
I tried but I get en error if I search with it (like unsupported operation)

**Comment by reta** [comment]
> I tried but I get en error if I search with it (like unsupported operation)

I suppose it should work at least for `NativeQuery` (`CriteriaQueryBuilder::build` + `NativeQueryBuilder::withQuery`), mind sharing the snippet and / or error you are getting?

**Comment by domenicofasano99** [comment]
@reta  the error that I receive is:
`org.springframework.data.elasticsearch.client.elc.NativeQuery

	at org.opensearch.data.client.orhlc.RequestFactory.getQuery(RequestFactory.java:1190)
	at org.opensearch.data.client.orhlc.RequestFactory.searchRequest(RequestFactory.java:764)
	at org.opensearch.data.client.orhlc.OpenSearchRestTemplate.search(OpenSearchRestTemplate.java:383)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.search(AbstractElasticsearchTemplate.java:453)
	at`

with this code:
`        Query aggregatedQuery = new NativeQueryBuilder()
                .withQuery(new CriteriaQuery(criteria))
                .withMaxResults(0)
                .withAggregation("sumAvailable", co.elastic.clients.elasticsearch._types.aggregations.AggregationBuilders
                        .sum(ta -> ta.field("availableAmountDelta")))
                .withAggregation("sumVat", co.elastic.clients.elasticsearch._types.aggregations.AggregationBuilders
                        .sum(ta -> ta.field("vatValue_value")))
                .build();

        SearchHits<TransactionDocument> searchHits = openSearchRestTemplate.search(aggregatedQuery, TransactionDocument.class);`

**Comment by reta** [comment]
@domenicofasano99  `org.springframework.data.elasticsearch.client.elc.NativeQuery` is not the correct type to use with OpenSearch, it should  be `org.opensearch.data.client.osc.NativeQuery`
