### ISSUE TITLE
[PROPOSAL] How about excluding ``opensearch-rest-client-sniffer`` dependency?

### ISSUE THREAD

**Issue by tuguri8** [opensearch-project/spring-data-opensearch#323]
### What are you proposing?
Hello, ``spring-data-opensearch`` seems to have ``opensearch-rest-client-sniffer`` dependency by default.
However, ``spring-data-elasticsearch`` doesn't have its dependency by default and Elastic said sniffing can be double-edged-sword.
> ref: https://www.elastic.co/blog/elasticsearch-sniffing-best-practices-what-when-why-how/

How about excluding ``opensearch-rest-client-sniffer`` dependency and leave it to the developers preference ?

As shown in the [issue](https://github.com/opensearch-project/spring-data-opensearch/issues/121), it seems more reasonable to add dependency only when needed, rather than removing them if an error occurs.
(If using a cluster provided by a cloud service like AWS Opensearch, we'll probably always get errors while sniffing nodes)

**Comment by tuguri8** [comment]
@reta Can you comment this for me?

**Comment by reta** [comment]
> @reta Can you comment this for me?

Thanks @tuguri8 , I think it causes more problems than benefits. we saw a couple of issues with sniffer when connecting toclusters in cloud-based environments or containers. Mind sending the pull request? Thank you!
