### ISSUE TITLE
[PROPOSAL] provide spring AutoConfiguration support

### ISSUE THREAD

**Issue by Maglore** [opensearch-project/spring-data-opensearch#34]
### What are you proposing?
Provide an AutoConfiguration for spring opensearch library like it is done for [elastisearch](https://github.com/spring-projects/spring-boot/tree/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/elasticsearch)

### What problems are you trying to solve?
Currently the RestClient has to be build from every user and every user has to define its own properties. 
This can unified and simplified with this configuration.

### What is the developer experience going to be?
This should ease the start of other spring developers with this library.

#### Are there any security considerations? 
No, even if done correctly some basic security configurations can be made here.

**Comment by dblock** [comment]
Good idea. Care to contribute @Maglore?

**Comment by reta** [comment]
I have opened https://github.com/spring-projects/spring-boot/pull/33011 so we could get Elasticsearch auto configuration out of our way (related issue is https://github.com/spring-projects/spring-boot/issues/33010)

**Comment by dlvenable** [comment]
Perhaps we should split this project into two modules:

1. The core module. It would depend only on Spring Data.
2. A Spring Boot starter with the auto configuration.

**Comment by reta** [comment]
+1 to have dedicated starter module, we also have an issue which I was trying to address in Spring Boot but it was rejected: we sadly have to find a way to exclude (may be using `AutoConfigurationExcludeFilter` or alike) to exclude the `ElasticsearchDataAutoConfiguration` since it needs the Elasticsearch Java Client no matter what.

**Comment by reta** [comment]
@Maglore if you are not working on it, I would like to pick it up so we should be ready for mid-November Spring / Spring Boot / Spring Data Elasticsearch releases, thanks!

**Comment by Maglore** [comment]
@reta, yes sry i have currently no time to work on it, sry for the late answer
