### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError on DeleteQuery with Spring Boot 3.2.2 and Opensearch Spring Data 1.5.3

### ISSUE THREAD

**Issue by riccardosaponi** [opensearch-project/spring-data-opensearch#366]
I have a spring boot microservice 
 - Spring Boot 3.2.2
I add these dependencies
`<dependency>
			<groupId>org.opensearch.client</groupId>
			<artifactId>spring-data-opensearch-starter</artifactId>
			<version>1.5.3</version>
			<exclusions>
				<exclusion>
					<groupId>org.opensearch.client</groupId>
					<artifactId>opensearch-rest-high-level-client</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.opensearch.client</groupId>
			<artifactId>opensearch-java</artifactId>
			<version>2.11.1</version>
		</dependency>`

I use OpenSearchTemplate to make query search.

When i start the microservice I obtain these error.
 - java.lang.NoClassDefFoundError: org/springframework/data/elasticsearch/core/query/DeleteQuery

In Maven Dependencies i see that OpenSearch 1.5.3 import org.springframework.data:spring-data-elasticsearch:5.2.2

OpenSearchTemplate import the class DeleteQuery. However this class is not present in spring-data-elastic:5.2.2

**Comment by reta** [comment]
@riccardosaponi please check the compatibility matrix [1], Spring Data Opensearch 1.5.x is compatible with Spring Data Elasticsearch 5.3.x. The Spring Boot 3.2.x brings Spring Data Elasticsearch 5.2.x, so you may need to update to this one or use Spring Data Opensearch 1.4.x release line.

[1] https://github.com/opensearch-project/spring-data-opensearch?tab=readme-ov-file#compatibility-matrix
