### ISSUE TITLE
[BUG] `HttpAsyncClientBuilder.defaultIOReactorConfig` gets overwritten by default `RestClientBuilderCustomizer`

### ISSUE THREAD

**Issue by nstdio** [opensearch-project/spring-data-opensearch#389]
### What is the bug?
Cannot configure `HttpAsyncClientBuilder.defaultIOReactorConfig` using `RestClientBuilderCustomizer` because default customizer overwrites it.

### How can one reproduce the bug?
Define a RestClientBuilderCustomizer and configure `HttpAsyncClientBuilder.defaultIOReactorConfig` and see that it does not have effect.

### What is the expected behavior?
To user defined `RestClientBuilderCustomizer` have effect regarding `HttpAsyncClientBuilder.defaultIOReactorConfig`.

### What is your host/environment?
Java: 21.0.5+11
Spring Data OpenSearch: 1.5.4
Spring Boot: 3.3.6

### Do you have any additional context?
I've tried to use `@Order` to force my customizer be applied last (by the way overwriting whatever changes were made by default customizer), but default one does not define any order so it'll come as lowest precedence.

**Comment by reta** [comment]
This one turned out to be tricky, `DefaultRestClientBuilderCustomizer` configures `IOReactorConfig::setSoKeepAlive` property and needs to alter the default `IOReactorConfig`. 

```java
        @Override
        public void customize(HttpAsyncClientBuilder builder) {
            builder.setDefaultCredentialsProvider(new ConnectionsDetailsCredentialsProvider(this.connectionDetails));
            map.from(this.properties::isSocketKeepAlive)
                    .to((keepAlive) -> builder.setDefaultIOReactorConfig(
                            IOReactorConfig.custom().setSoKeepAlive(keepAlive).build()));
        }

```

The `HttpAsyncClientBuilder` does not provide the way to chek if the default `IOReactorConfig` has been configured already.

**Comment by reta** [comment]
@nstdio so for your particular case, the workaround would be to change the customizer order so your `RestClientBuilderCustomizer` will be applied last, overriding the default `IOReactorConfig`.

```
    @Bean
    static BeanFactoryPostProcessor beanFactoryPostProcessor() {
        return new BeanFactoryPostProcessor() {
            @Override
            public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
                beanFactory.getBeanDefinition("defaultRestClientBuilderCustomizer")
                    .setAttribute(AbstractBeanDefinition.ORDER_ATTRIBUTE, Ordered.HIGHEST_PRECEDENCE);
            }
        };
    }
```
