### ISSUE TITLE
[FEATURE] https connection using Spring Boot SSL Bundle

### ISSUE THREAD

**Issue by aivish** [opensearch-project/spring-data-opensearch#396]
### Is your feature request related to a problem?
When connecting to OpenSearch via https it would be nice to configure in properties which SSL Bundle to use. There already seem to be some properties for this:
```
opensearch:
  uris: https://opensearch-host:9200
  restclient:
    ssl:
      bundle: example

spring:
  ssl:
    bundle:
      pem:
        example:
          truststore:
            certificate: file:/path/to/opensearch.ca
```
But unless I'm doing something wrong the bundle is not used, maybe those properties are just there because `OpenSearchProperties` uses `Restclient` properties from Elasticsearch.

For this configuration to work I had to create custom `RestClientBuilderCustomizer`  with something like this:
```
@Override
public void customize(HttpAsyncClientBuilder builder) {
    String sslBundleName = properties.getRestclient().getSsl().getBundle();
    if (StringUtils.hasText(sslBundleName)) {
        SslBundle sslBundle = sslBundles.getBundle(sslBundleName);
        SSLContext sslcontext = sslBundle.createSslContext();
        SslOptions sslOptions = sslBundle.getOptions();

        builder.setSSLContext(sslcontext);
        builder.setSSLStrategy(new SSLIOSessionStrategy(sslcontext, sslOptions.getEnabledProtocols(), sslOptions.getCiphers(), (HostnameVerifier) null));
    }
}
```

Maybe this should be part of `OpenSearchRestClientConfigurations`, applied by the `DefaultRestClientBuilderCustomizer` or set as part of `opensearchRestClientBuilder`? Elasticsearch autoconfiguration is doing something similar here - https://github.com/spring-projects/spring-boot/blob/v3.4.0/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/elasticsearch/ElasticsearchRestClientConfigurations.java#L97.

### What solution would you like?
Configure `opensearch.restclient.ssl.bundle` without needing to create any additional `RestClientBuilderCustomizer`'s .

### What alternatives have you considered?
Create `RestClientBuilderCustomizer` or add my OpenSearch CA to global trust store (probably would work, but didn't try, don't really want to do that).

### Do you have any additional context?
If this makes sense and looks reasonable I can try creating PR for this.

**Comment by reta** [comment]
Thanks @aivish , I think the enhancement in general does make sense, but we have to think about SSL hot reload for SSL bundles. Or, at least, warn the users if the hot reload won't be supported. The pull request will be much appreciated, thank you.

[1] https://spring.io/blog/2023/11/07/ssl-hot-reload-in-spring-boot-3-2-0

**Comment by aivish** [comment]
did not know about the hot reload, will take a look after the holidays

**Comment by d31m07y1988** [comment]
hmm, I'm doing the same thing
