### ISSUE TITLE
[BUG] Can not import jar to spring-boot app

### ISSUE THREAD

**Issue by boriskezikov** [opensearch-project/spring-data-opensearch#77]
### What is the bug?
I am trying to add dependency to my app and it doesnt work. Also i don;t see any versions released anywhere.

### How can one reproduce the bug?
add     implementation ("org.opensearch:spring-data-opensearch") to your gradle.build

**ERROR**: backend:test: Could not find org.opensearch:spring-data-opensearch:.
Required by:
    project :

how can i use this library?

**Comment by juferdinand** [comment]
https://github.com/opensearch-project/spring-data-opensearch/issues/8

Not yet released on maven central, u have to download the project and build it by yourself. Unlucky that I get anytime error xD

If u can build it, can u maybe share the jar?

**Comment by boriskezikov** [comment]
Do we have any understanding when it will be released?

Because i want to start a project with spring and opensearch but if there is no valid library for this i will have to consider using elasticsearch instead.. 


@juferdinand regarding to your question, a cant build it locally unfortunatelly(

**Comment by juferdinand** [comment]
I found nothing about when it will be released. This is why I switched also to Elasticsearch now, also if the licence of them is not great. But for me it would still free.

Maybe the Maintainer can say soon something about it 

@boriskezikov

**Comment by exZStas** [comment]
Any ideas when 1.0.0 will be released on maven central? 🙂

**Comment by reta** [comment]
@exZStas still waiting for https://github.com/opensearch-project/spring-data-opensearch/pull/75 :(

**Comment by dlvenable** [comment]
@boriskezikov , This is now available as 1.0.0.

You can see the artifact here:

https://central.sonatype.com/artifact/org.opensearch.client/spring-data-opensearch/1.0.0

And the instructions on the main page are updated. https://github.com/opensearch-project/spring-data-opensearch

**Comment by boriskezikov** [comment]
Unbelievable !
