### ISSUE TITLE
[PROPOSAL] Release v1.

### ISSUE THREAD

**Issue by dblock** [opensearch-project/spring-data-opensearch#8]
### What are you proposing?

Release v1.

### What users have asked for this feature?

All users that want OpenSearch integration for spring-data.

### Any remaining open questions?

Please add your +1 if you're interested in a release.

**Comment by dlvenable** [comment]
I think it would be nice to start creating `0.x` releases to get the project moving quickly.

**Comment by juferdinand** [comment]
I would need an release fast, any information when it will released?

**Comment by reta** [comment]
@dblock we are ready to 1.0.0, could you look at https://github.com/opensearch-project/spring-data-opensearch/pull/75?

**Comment by dlvenable** [comment]
This is available: https://github.com/opensearch-project/spring-data-opensearch/releases/tag/1.0.0

**Comment by luisalves00** [comment]
@dlvenable  are you pushing to maven central as well?

**Comment by reta** [comment]
It is on Maven Central: https://mvnrepository.com/artifact/org.opensearch.client/spring-data-opensearch-starter

**Comment by luisalves00** [comment]
@reta Thanks, I think it's not yet indexed, as I search and cannot find it.
