### ISSUE TITLE
[PROPOSAL] Add support for spring-boot 2.7

### ISSUE THREAD

**Issue by debraj-manna** [opensearch-project/spring-data-opensearch#89]
### What are you proposing?

`spring-data-opensearch` should also add support for spring-boot 2.7. As per the README now spring-boot is compatible only with 3.0 and above.

### What problems are you trying to solve?

Upgrading to spring-boot 3.0 has to go through 2.7 as mentioned [here](https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0). So adding support for spring-boot 2.7 also in `spring-data-opensearch` will cause earlier adoption.

**Comment by reta** [comment]
@debraj-manna the long story why only Spring Boot 3.x is supported is here [1] but in short: `spring-data-opensearch` is built on top of `spring-data-elasticsearch`, the necessary code changes which allowed `OpenSearch` support went into  version 5.0 of the `spring-data-elasticsearch` and that's the minimal version we could use (which means Spring Boot 3.0 baseline). 

Supporting Spring Boot 2.x line at the moment requires literally forking `spring-data-elasticsearch` 4.x and rewriting it for `OpenSearch`.

[1] https://github.com/spring-projects/spring-data-elasticsearch/issues/1918

**Comment by debraj-manna** [comment]
Ok. We will then first upgrade to spring-boot 3.0 and then try to use `spring-data-opensearch`.
