### ISSUE TITLE
[PROPOSAL] Publish -SNAPSHOT builds to Maven

### ISSUE THREAD

**Issue by dblock** [opensearch-project/spring-data-opensearch#9]
### What are you proposing?

Publish -SNAPSHOTs to maven.

### What users have asked for this feature?

Everyone who wants to test drive daily builds.

**Comment by michaelboyles** [comment]
Can you at least change the readme until this is completed? The readme implies this is already available and it isn't.

**Comment by Alienmova** [comment]
I am waiting this library. Please added it.

**Comment by dblock** [comment]
@michaelboyles @Alienmova come help with some other items in https://github.com/opensearch-project/spring-data-opensearch/issues!
