### ISSUE TITLE
[BUG] Not support SpringBoot version 2.7.X

### ISSUE THREAD

**Issue by kqiang** [opensearch-project/spring-data-opensearch#91]
### What is the bug?
Got the following errors in SpringBoot startup when using it with SpringBoot 2.7.X

2023-01-30 10:28:10.782  INFO 30405 --- [           main] c.e.o.OpenSearchClientPocApplication     : No active profile set, falling back to 1 default profile: "default"
2023-01-30 10:28:11.240  INFO 30405 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Elasticsearch repositories in DEFAULT mode.
2023-01-30 10:28:11.329 ERROR 30405 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.data.elasticsearch.repository.config.ElasticsearchRepositoryConfigExtension.getModulePrefix(ElasticsearchRepositoryConfigExtension.java:64)

The following method did not exist:

    'java.lang.String org.springframework.data.elasticsearch.repository.config.ElasticsearchRepositoryConfigExtension.getModuleIdentifier()'

The calling method's class, org.springframework.data.elasticsearch.repository.config.ElasticsearchRepositoryConfigExtension, was loaded from the following location:

    jar:file:/Users/kewei/.gradle/caches/modules-2/files-2.1/org.springframework.data/spring-data-elasticsearch/5.0.0/86f7d0d3ac9be7d3dfef1b37a0850852c8c1d9e8/spring-data-elasticsearch-5.0.0.jar!/org/springframework/data/elasticsearch/repository/config/ElasticsearchRepositoryConfigExtension.class

The called method's class, org.springframework.data.elasticsearch.repository.config.ElasticsearchRepositoryConfigExtension, is available from the following locations:

    jar:file:/Users/kewei/.gradle/caches/modules-2/files-2.1/org.springframework.data/spring-data-elasticsearch/5.0.0/86f7d0d3ac9be7d3dfef1b37a0850852c8c1d9e8/spring-data-elasticsearch-5.0.0.jar!/org/springframework/data/elasticsearch/repository/config/ElasticsearchRepositoryConfigExtension.class

The called method's class hierarchy was loaded from the following locations:

    org.springframework.data.elasticsearch.repository.config.ElasticsearchRepositoryConfigExtension: file:/Users/kewei/.gradle/caches/modules-2/files-2.1/org.springframework.data/spring-data-elasticsearch/5.0.0/86f7d0d3ac9be7d3dfef1b37a0850852c8c1d9e8/spring-data-elasticsearch-5.0.0.jar
    org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport: file:/Users/kewei/.gradle/caches/modules-2/files-2.1/org.springframework.data/spring-data-commons/2.7.2/9547d1234cb380234066aef60129bb2ddfdc6347/spring-data-commons-2.7.2.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.data.elasticsearch.repository.config.ElasticsearchRepositoryConfigExtension

Process finished with exit code 1

### How can one reproduce the bug?
_Steps to reproduce the behavior._
Use the following build.gradle
plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.2'
    id 'io.spring.dependency-management' version '1.1.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-jetty")
    implementation("org.springframework.boot:spring-boot-starter-web")

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation "org.opensearch.client:spring-data-opensearch:0.1.0"
    implementation 'org.springframework.data:spring-data-elasticsearch:5.0.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
    useJUnitPlatform()
}

### What is the expected behavior?
_A clear and concise description of what you expected to happen._
The SpringBoot app should start without any errors.

### What is your host/environment?
_Operating system, version._
MacOs Monterey version 12.6

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._
No

### Do you have any additional context?
_Add any other context about the problem._
It works well with SpringBoot version 3.0.0

**Comment by reta** [comment]
@kqiang please refer to https://github.com/opensearch-project/spring-data-opensearch/issues/89 and https://github.com/opensearch-project/spring-data-opensearch#about-opensearch-versions-and-clients
